#!/usr/bin/env bash

pandoc -t html5 -V lang=en --section-divs --template=template/template.html5  \
       --smart --email-obfuscation=none document-structure.txt \
       > unstyled.html
css --style=css/style.css unstyled.html > index.html
rm unstyled.html

pandoc --template=template/template.latex -o document-structure.pdf \
       document-structure.txt

